site_name: CommitOps Learning
site_url: https://commitops.co.in/
# site_url: https://commitops.co.in/
# material theme default plugins as below
# plugins:
#   - blog
#   - group
#   - offline
#   - search
#   - social
#   - tags

theme:
  name: material
  # name: dracula
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs
    - announcement.bar
    - announcement.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - header.autohide
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  announcement:
    type: info
    text: |
      ðŸš€ New DevOps tutorials added! [Explore Now](./devops/)

plugins:
  - search
  - minify
  - awesome-nav
  - include_dir_to_nav
  - mkdocs-pdf
  # - blog
  - tags
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
      cache: 600
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # - toc:
  #     permalink: true

extra_css:
  - assets/stylesheets/extra.css
  # - assets/stylesheets/footer.css
  # - assets/stylesheets/thm.css
  # - assets/stylesheets/ai-summary.css
  # - assets/stylesheets/termynal.css
  # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

# extra_javascript:
#   - assets/javascripts/terminal-anim.js
  # - assets/javascripts/color.js
  # - assets/javascripts/termynal.js
  # - assets/javascripts/gen_termynal.js

# nav:
#   - Home: index.md
#   - AWS QnA: aws-qna/aws-questions-answers.md
#   - Code: code.md