site_name: CommitOps Learning
site_url: https://mydomain.org/mysite
# material theme default plugins as below
# plugins:
#   - blog
#   - group
#   - offline
#   - search
#   - social
#   - tags

theme:
  name: dracula
  # custom_dir: docs/overrides
  custom_dir: overrides/partials
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: dracula/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: dracula/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - minify
  - awesome-nav
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
      cache: 600
  - include_dir_to_nav
  # - tags:
  #     tags_file: tags.md
  # - blog
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/footer.css
  # - assets/stylesheets/thm.css
  # - assets/stylesheets/ai-summary.css
  # - assets/stylesheets/termynal.css
  # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

# extra_javascript:
#   - assets/javascripts/terminal-anim.js
  # - assets/javascripts/color.js
  # - assets/javascripts/termynal.js
  # - assets/javascripts/gen_termynal.js

nav:
  - Home: index.md
  - AWS QnA: aws-qna/aws-questions-answers.md
  - Code: code.md